name: pre-commit
on: pull_request

env:
  PYTEST_RUN_PATH: Packs/Qradar/Integrations/Qradar_v3
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
    - name: Install poetry
      run: pipx install poetry

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup python

      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'poetry'
    - name: Install dependencies
      run: poetry install

    - name: get full demisto-sdk python-version
      id: get-python-version
      run: |
        echo poetry show demisto-sdk
    - uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: pre-commit-3|${{ env.pythonLocation }}

    - name: annotate in files
      run: echo "::error file=Packs/QRadar/Integrations/QRadar_v3/QRadar_v3.py,line=2,col=3::This is an error"
    - name: run pre-commit
      run: poetry run demisto-sdk pre-commit -g --test
